# Generated by Django 4.2 on 2025-11-06 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"managed": False},
        ),
    ]
