# Generated by Django 4.2 on 2025-11-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_dailyorder_dailyrecipeorder_inventory_order_recipe_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "recipe_ingredient",
                "managed": False,
            },
        ),
    ]
