# Generated by Django 4.2 on 2025-11-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipeingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'recipes',
                'managed': False,
            },
        ),
    ]
