# Generated by Django 4.2 on 2025-11-24 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customeritem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerItem',
        ),
    ]
