"""
Django settings for PandaPOS project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY", default="django-insecure-demo-key-change-in-production")

EXTERNAL_API_KEY = config("API_KEY_EXTERNAL_SERVICE", default=os.getenv("API_KEY_EXTERNAL_SERVICE", ""))

AZURE_TRANSLATOR = {
    "KEY": config("AZURE_TRANSLATION_KEY", default=os.getenv("AZURE_TRANSLATION_KEY", "")),
    "REGION": config("AZURE_TRANSLATION_REGION", default=os.getenv("AZURE_TRANSLATION_REGION", "")),
    "ENDPOINT": config("AZURE_TRANSLATION_ENDPOINT", default=os.getenv("AZURE_TRANSLATION_ENDPOINT", "")),
}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '.herokuapp.com',  # For Heroku deployment
    '.onrender.com',   # For Render deployment
]

# Trusted origins for CSRF protection
CSRF_TRUSTED_ORIGINS = [
    'https://*.herokuapp.com',
    'https://*.onrender.com',
]



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "apps.customer_kiosk",
    "apps.cashier",
    "apps.kitchen",
    "apps.manager",
    "apps.menu",
    "apps.inventory",
    "apps.homePage",
    "core",
    "apps.orders",
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_FORMS = {
    "reset_password": "apps.homePage.forms.QRResetPasswordForm",
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',  # just added
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "panda_config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "panda_config.wsgi.application"
ASGI_APPLICATION = "panda_config.asgi.application"

# Channels: use in-memory channel layer for development
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='panda_express_demo'),
        'USER': config('DB_USER', default='your_db_user'),
        'PASSWORD': config('DB_PASSWORD', default='your_db_password'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"  # was "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# Cache static assets (including images) for a year when hashed
WHITENOISE_MAX_AGE = 31536000

# Let WhiteNoise use staticfiles finders in dev (so collectstatic is not required)
WHITENOISE_USE_FINDERS = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Google OAuth Settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'prompt': 'select_account',  # Force account selection every time
        },
        'APP': {
            'client_id': config('GOOGLE_OAUTH_CLIENT_ID', default=os.getenv('GOOGLE_OAUTH_CLIENT_ID', '')),
            'secret': config('GOOGLE_OAUTH_CLIENT_SECRET', default=os.getenv('GOOGLE_OAUTH_CLIENT_SECRET', '')),
            'key': ''
        }
    }
}

# Allauth settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Allow password reset without email verification
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = False  # Don't logout after password change
ACCOUNT_SESSION_REMEMBER = False  # Disable persistent sessions / "remember me"
ACCOUNT_ADAPTER = 'apps.homePage.adapters.SafeAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'apps.homePage.adapters.AutoConnectSocialAccountAdapter'

LOGIN_REDIRECT_URL = '/kiosk/'
LOGOUT_REDIRECT_URL = '/'


# Email backend settings 
# Use Azure Communication Services for all email sending (including password reset)
if os.environ.get('EMAIL_HOST_PASSWORD'):
    # Use Azure custom email backend
    EMAIL_BACKEND = "core.backends.azure_email_backend.AzureEmailBackend"
    DEFAULT_FROM_EMAIL = os.environ.get('AZURE_EMAIL_SENDER', 'DoNotReply@azurecomm.net')
else:
    # Fallback to console backend (prints emails to console/logs)
    # This prevents errors when email isn't configured or SMTP ports are blocked
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = 'pandaposteam52@gmail.com'

# Azure Communication Services Email Settings
AZURE_EMAIL_CONNECTION_STRING = os.environ.get('AZURE_EMAIL_CONNECTION_STRING', '')
AZURE_EMAIL_SENDER = os.environ.get('AZURE_EMAIL_SENDER', 'pandapsteam52@gmail.com')
