# Generated by Django 4.2 on 2025-11-10 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='RecipeOrder',
        ),
    ]
